/*import localFont from "next/font/local";
import "./globals.css";

const geistSans = localFont({
  src: "./fonts/GeistVF.woff",
  variable: "--font-geist-sans",
  weight: "100 900",
});
const geistMono = localFont({
  src: "./fonts/GeistMonoVF.woff",
  variable: "--font-geist-mono",
  weight: "100 900",
});

*/

import { Inter } from "next/font/google";
import "./globals.css";
import { ThemeProvider } from "./ThemeProvider";



const  inter = Inter ({ subsets: ["latin"] });

export const metadata = {
  title: "DentalCleene",
  description: "Generated by create next app",
};



export default function RootLayout({ children }) {





  return (
    <html lang="en">
      <body className={inter.className}>
      <ThemeProvider
             attribute="class"
            defaultTheme="system"
            enableSystem
            disableTransitionOnChange
      >
        {children}
      </ThemeProvider>  
      </body>
    </html>
  );



}
